url: "https://mlcolearn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MLCoLearn" # the name of your site, e.g. ACME Corp.
description: "Collaboratively Exploring ML Algorithms for Neuroscience Research"
